services:
  simulcast-mpv-relay:
    #user: 1000:1000
    build: .
    restart: unless-stopped
    stop_grace_period: 2s
    environment:
      - SIMULCAST_BIND_ADDRESS=0.0.0.0
      - SIMULCAST_REPO_URL=${SIMULCAST_REPO_URL}
    ports:
      # Default SIMULCAST_BIND_PORT.
      - "127.0.0.1:30777:30777"
