services:
  simulcast-mpv-relay:
    #user: 1000:1000
    build: .
    restart: unless-stopped
    environment:
      - SIMULCAST_BIND_ADDRESS=0.0.0.0
    ports:
      # Default SIMULCAST_BIND_PORT.
      - "127.0.0.1:30777:30777"
